[build]
  base = "frontend/"
  publish = "frontend/build"
  command = "npm ci --prefer-offline --no-audit && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_URL = "/api"
  REACT_APP_WEBSOCKET_URL = "wss://jurisia-api.onrender.com"
  REACT_APP_ENV = "production"
  REACT_APP_VERSION = "2.0.0"
  REACT_APP_APP_NAME = "JurisIA"
  REACT_APP_DEBUG = "false"
  REACT_APP_MAX_FILE_SIZE = "10485760"
  REACT_APP_ALLOWED_FILE_TYPES = ".pdf,.doc,.docx,.txt,.rtf"
  REACT_APP_THEME = "light"
  REACT_APP_LOCALE = "pt-BR"
  REACT_APP_TIMEZONE = "America/Sao_Paulo"
  REACT_APP_ENABLE_ANALYTICS = "true"
  REACT_APP_ENABLE_WEBSOCKET = "true"
  REACT_APP_ENABLE_AI_FEATURES = "true"
  REACT_APP_ENABLE_REAL_TIME = "true"

# === CONFIGURAÇÕES DE CONTEXTO ===
[context.production]
  command = "cd frontend && npm ci --prefer-offline --no-audit && npm run build"

[context.deploy-preview]
  command = "cd frontend && npm ci --prefer-offline --no-audit && npm run build"

[context.branch-deploy]
  command = "cd frontend && npm ci --prefer-offline --no-audit && npm run build"

# === REDIRECTS PARA API ===
[[redirects]]
  from = "/api/*"
  to = "https://jurisia-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"}

# Health check
[[redirects]]
  from = "/health"
  to = "https://jurisia-api.onrender.com/health"
  status = 200
  force = true

# SPA routing - DEVE SER A ÚLTIMA REGRA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# === HEADERS DE SEGURANÇA ===
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# === HEADERS CORS PARA API ===
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

# === CACHE OTIMIZADO ===
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.{png,jpg,jpeg,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.{woff,woff2,ttf,otf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para manifest e service worker
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# === PROCESSAMENTO E OTIMIZAÇÃO ===
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 