services:
  # Backend API
  - type: web
    name: jurisia-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - src.app:app
    plan: starter
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jurisia-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://jurisia.netlify.app,https://*.netlify.app,http://localhost:3000"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "10000"

  # PostgreSQL Database
  - type: pserv
    name: jurisia-db
    env: postgres
    plan: starter
    region: oregon
    
  # Redis Cache
  - type: pserv  
    name: jurisia-redis
    env: redis
    plan: starter
    region: oregon 

databases:
  - name: jurisia-db
    databaseName: jurisia
    user: jurisia_user
    plan: starter
    region: oregon 